const contents = [
    {
        chapter1: {
        heading_english: `Chapter-1`,
        heading_kannada: `ಅಧ್ಯಾಯ-೧`,
        english_p1: `Gajanana, when you sway your expansive ears, the ensuing wind dispels obstacles. The Brahma deities venerate you, who, before commencing any endeavor, chant Vedas, Shastras, and Puranas. Please illuminate my intellect. Our lineage traces back to Sayandeva, also known as 'Sakhare,' of the Kaundinya Maharishi gotra from the Apastamba branch. 'Gangadhara' from the same lineage is my father. I go by the name Saraswati, and later on, I acquired the appellation 'Saraswati Gangadhar'.`,
        kannada_p1: `ಗಜಾನನ, ನೀನು ನಿನ್ನ ಎರಡು ಅಗಲವಾದ ಕಿವಿಗಳನ್ನ ಅಲುಗಾಡಿಸಿದಾಗ ಹುಟ್ಟುವ ಗಾಳಿಯು ವಿಘ್ನವನ್ನು ನಾಶ ಮಾಡುತ್ತದೆ. ಬ್ರಹ್ಮಾದಿ ದೇವತೆಗಳು ವೇದ, ಶಾಸ್ತ್ರ, ಪುರಾಣಗಳನ್ನು ಹೇಳಿದ ನಿನ್ನನ್ನು ಎಲ್ಲಾ ಕಾರ್ಯಾರಂಭಕ್ಕು ಮುನ್ನ ಪೂಜಿಸುತ್ತಾರೆ. ನೀನು ನನ್ನ ಬುದ್ಧಿಯನ್ನು ಪ್ರಕಾಶಿಸಬೇಕು. ಆಪಸ್ತಂಭ ಶಾಖೆಯ ಕೌಂಡಿಣ್ಯ ಮಹಾಋಷಿ ಗೋತ್ರದ 'ಸಾಖರೆ' ಎಂಬ ಅಡ್ಡ ಹೆಸರಿನ ಸಾಯಂದೇವ ಎಂಬುವನು ನಮ್ಮ ಕುಲದ ಮೂಲ ಪುರುಷನಾಗಿದ್ದು, ಇದೇ ವಂಶದ 'ಗಂಗಾಧರ' ಎಂಬುವವನು ನನ್ನ ತಂದೆ. ನನ್ನ ಹೆಸರು ಸರಸ್ವತಿ. ಅನಂತರ ನನಗೆ 'ಸರಸ್ವತಿ ಗಂಗಾಧರ' ಎಂಬ ಹೆಸರು ಬಂದಿತು.`,
        kannada_h1: `ಶ್ರೀ ಗುರುಗಳ ಪ್ರೇರೆಪಣೆಯಂತೆ ಈಗ ನಾನು ಗುರುಚರಿತ್ರೆಯನ್ನು ಹೇಳುತ್ತೇನೆ.`,
        english_h1: `I will now narrate Gurucharitra under the guidance of Sri Guru.`,
        kannada_p2: `ಗಾಣಗಾಪುರದಲ್ಲಿ ಶ್ರೀ ಗುರುಗಳ ಹೆಸರು ಪ್ರಖ್ಯಾತಿ ಪಡೆದಿತ್ತು ಈ ಸಮಯದಲ್ಲಿ ನಾಮಾಧಾರಕ ಎಂಬ ಒಬ್ಬ ಭಕ್ತ ಗುರುಗಳ ದರ್ಶನಕ್ಕೆ ಗಾಣಗಾಪುರಕ್ಕೆ ಹೋಗಬೇಕು ಅಲ್ಲಿ ಅವರ ದರ್ಶನವಾಗದಿದ್ದರೆ ಪ್ರಾಣ ತ್ಯಾಗ ಮಾಡಬೇಕು ಎಂದು ನಿಶ್ಚಯಿಸಿದನು. ನಾಮಧಾರಕನ ಮನಸ್ಸಿನಲ್ಲಿ ಗುರುಗಳ ಕೃಪೆ ತನ್ನ ಮೇಲಿಲ್ಲ , ಗುರುಗಳು ಅವನನ್ನು ತಿರಸ್ಕರಿಸುತ್ತಿದ್ದಾರೆ, ಗುರುಗಳಿಗೆ ಏನನ್ನಾದರು ಕೊಟ್ಟವರಿಗೆ ಮಾತ್ರ ಗುರುಗಳು ಅನುಗ್ರಹಿಸುತ್ತಾರೆ ಎಂಬ ಆಲೋಚನೆ ಇತ್ತು. ದಾರಿಯುದ್ದಕ್ಕು ಅವನು ತನ್ನ ಮನಸ್ಸಿನಲ್ಲಿಯೇ ಗುರುಗಳಿಗೆ ಏಕೆ ನನ್ನ ಬಗ್ಗೆ ನಿಮಗೆ ಕರುಣೆ ಬರುವುದಿಲ್ಲ, ಸದಾ ನಿಮ್ಮನ್ನೇ ಜಪಿಸಿದರು ನಿಮ್ಮ ಅನುಗ್ರಹ ನನ್ನ ಮೇಲಾಗಿಲ್ಲ. ನನ್ನ ಮೇಲೆ ನಿನಗೆ ದ್ವೇಷ ಇರಲು ಕಾರಣವಾದರು ಏನು ಹೀಗೆಲ್ಲ ಹುಚ್ಚನಂತೆ ಪ್ರಶ್ನೆ ಕೇಳುತ್ತ ಹೋಗುತ್ತಿದ್ದ. ಬಹಳ ಸಮಯ ನಡೆದು ದಣಿವಾದ ಕಾರಣ ಅಲ್ಲೇ ಮರದಡಿ ಮಲಗಿರಲು ಗಾಢವಾದ ನಿದ್ರೆಗೆ ಜಾರಿದನು.`,
        english_p2: `The renowned name of Sri Guru echoed in Gangapur. During this period, a devoted soul named Namadharaka made a firm decision to journey to Gangapur to seek the Guru's divine presence. Filled with the conviction that if he couldn't have the Guru's darshan, he would relinquish his own life, Namadharaka harbored a belief that the Guru's blessings were elusive to him. In his perception, the Guru seemed to favor only those who offered something in return. Throughout his journey, Namadharaka incessantly questioned within, pleading with the Guru for mercy, feeling a lack of grace. His desperate queries echoed like an incessant plea, wondering why the Guru appeared indifferent towards him. Exhausted from the long trek, he eventually succumbed to a profound slumber beneath the sheltering branches of a tree.`,
        kannada_p3: `ಈ ರೀತಿ ದೈನ್ಯತೆಯಿಂದ ಕೇಳಿದ ಎಲ್ಲಾ ಪ್ರಶೆಗಳಿಗೆ ಉತ್ತರಿಸಲು, ಮಗುವಿನ ಬಳಿ ತಾಯಿ ಓಡಿ ಬರುವಂತೆ, ನಾಮಾಧಾರಕನ ಸ್ವಪ್ನದಲ್ಲಿ ಶ್ರೀ ನೃಸಿಂಹ ಸರಸ್ವತಿ ಗುರುಗಳು ಕಾಣಿಸಿಕೊಂಡರು. ನಾಮಾಧಾರಕನ ಭಕ್ತಿಯ ಪರಾಕಾಷ್ಟೆ ಎಷ್ಟಿತ್ತೆಂದರೆ, ಸ್ವಪ್ನದಲ್ಲಿಯೇ ಗುರುಗಳ ಪಾದಪೂಜೆ ಮಾಡಿ, ಅವರನ್ನು ಸ್ತುತಿಗೈದು ಆನಂದಭರಿತನಾದನು.`,
        english_p3: `In Namadharaka's dream, Sri Nrisimha Saraswati Guru manifested with the tender care of a mother rushing to console a distressed child, addressing each of the pitifully posed questions. The devotee's profound devotion reached its pinnacle as he worshipped the Guru's feet within the dream, offering heartfelt praises, and basking in a state of bliss.`,
        kannada_h2:` ಈ ಅಧ್ಯಾಯದ ಸಾರಾಂಶ, ನಿಜವಾದ ಭಕ್ತರ ಮನಸ್ಸಿನಲ್ಲಿ ಗುರುಗಳು ಸದಾ ವಾಸಿಸುತ್ತಾರೆ ಎನ್ನುವುದಾಗಿದೆ`,
        img1: `/Images/nmd.jpeg`,
        img2: `/Images/dream.jpeg`,
        img1_title_english: `Namadharaka's  journey to Ganagapura eagerly seeking the divine darshan of the Guru.`,
        img1_title_kannada: ` ಗುರುಗಳನ್ನು ಕಾಣಲು ನಾಮಾಧಾರಕ ಗಾಣಗಾಪುರದ ಕಡೆಗೆ ಹೋಗುತ್ತಿರುವುದು`,
        img2_title_english: `Namadharaka witnessing Guru in his dream`,
        img2_title_kannada: `ನಾಮಾಧಾರಕನ ಕನಸಿನಲ್ಲಿ ಗುರಗಳು ದರ್ಶನ ನೀಡುವುದು`
    },
        chapter2:{
            heading_english: `Chapter-2`,
            heading_kannada: `ಅಧ್ಯಾಯ-೨`,
            english: `After dreaming about his Guru, Namadharaka woke up with the Guru still on his mind. As he continued his journey, he once again saw the Guru in his dream, approaching him. The Yativaryas, who turned out to be disciples of Sri Nrisimha Saraswati Guru, shared that they considered their Guru to be an incarnation of the Trinity and mentioned residing in Gangapur, where the Bhima and Amaraja rivers meet.
            Curious about the challenges he was facing despite having devotion to his Guru, Namadharaka asked for an explanation. The Yatis replied that his difficulties stemmed from a lack of steadfast faith in the Guru. They emphasized the Guru's omnipotence, stating that when Hari and Hara are displeased, the Guru can offer protection, but if the Guru is angered, neither Hari nor Hara can save. In response to this, Namadharaka sought clarification on where this belief in the Guru's omnipotence is mentioned in scriptures or Puranas.`,
            kannada_p1: `ನಾಮಾಧಾರಕನು ಕನಸಿನಲ್ಲಿ ಗುರುಗಳನ್ನ ಕಂಡ ನಂತರ ಎಚ್ಚರವಾಗಿ ಮತ್ತೆ ಗುರುವನ್ನ ನೆನಯುತ್ತ ಮುಂದೆ ಸಾಗಿದನು, ಸ್ವಲ್ಪ ದೂರ ಹೋದ ನಂತರ ಕನಸಿನಲ್ಲಿ ಕಂಡ ಗುರುಗಳು ತನ್ನ ಎದುರಿನಲ್ಲೆ ಬರುತ್ತಿರುವುದನ್ನು ಕಂಡು ಕೂಡಲೇ ಅವರಿಗೆ ನಮಸ್ಕರಿಸಿದನು ಮತ್ತು ಅವರಿಗೆ ತಮ್ಮ ಹೆಸರೇನು, ತಾವು ವಾಸಿಸುವ ಸ್ಥಳ ಯಾವುದು ಎಂದು ಕೇಳಿದನು. ಆಗ ಆ ಯತಿವರ್ಯರು ನಾವು ಶೀ ನೃಸಿಂಹ ಸರಸ್ವತಿ ಗುರುಗಳ ಶಿಷ್ಯರಾಗಿದ್ದೇವೆ. ಶ್ರೀ ನೃಸಿಂಹ ಸರಸ್ವತಿ ಯತಿಗಳು ತ್ರೈಮೂರ್ತಿ ಅವತಾರಿಗಳಾಗಿದ್ದಾರೆ. ಅವರು ಭೀಮಾ-ಅಮರಜಾ ಸಂಗಮದಲ್ಲಿರುವ ಗಾಣಗಾಪುರದಲ್ಲಿ ಅವರ ವಾಸ ಎಂದರು. ಅನಂತರ ನಾಮಾಧಾರಕನು, ನನ್ನಲ್ಲಿ ಗುರು ಭಕ್ತಿ ಇದ್ದರು ಸಹ ನನಗೇಕೆ ಈ ಪರಿಯ ಕಷ್ಟ ಎಂದು ಪ್ರಶ್ನೆಗಳನ್ನ ಕೇಳಿದನು. ಇದಕ್ಕೆ ಉತ್ತರವಾಗಿ ಯತಿಗಳು ನಿನ್ನ ಮನಸ್ಸಿನಲ್ಲಿ ಗುರುಗಳ ಬಗ್ಗೆ ಧೃಡ ನಂಬಿಕೆ ಇಲ್ಲದ ಕಾರಣ ನಿನ್ನ ಉದ್ಧಾರವಾಗಿಲ್ಲ. ಗುರುಗಳು ಸರ್ವ ಶಕ್ತರು. ಹರಿ-ಹರರು ಸಿಟ್ಟಿಗೆದ್ದರೆ ಗುರು ರಕ್ಷಿಸಬಲ್ಲರು ಅದೇ ಗುರುವೇ ಸಿಟ್ಟಿಗೆದ್ದರೆ ಹರಿ-ಹರರು ರಕ್ಷಿಸಲಾಗುವುದಿಲ್ಲ ಎಂದರು. ಇದನ್ನು ಕೇಳಿದಾಗ ನಾಮಾಧಾರಕನು, ಗುರುವು ಸರ್ವ ಶಕ್ತ ಎಂದು ಯಾವ ಶಾಸ್ತ್ರ - ಪುರಾಣಗಳಲ್ಲಿ ಉಲ್ಲೇಖವಾಗಿದೆ ಎಂದು ಕೇಳಿದನು`,
            kannada_h1: `ನಾಮಾಧರಕನ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರದಂತೆ ಯತಿಗಳು ನಾಲ್ಕು ಯುಗಗಳ ವರ್ಣನೆ ಮತ್ತು ಗುರು ಮಹಿಮೆಯನ್ನು ಹೇಳತೊಡಗಿದರು`,
            kannada_p2: `ನಾಮಧಾರಕ ಕೇಳು, ನಾರಾಯಣನು ವಟಪತ್ರದ ಮೇಲೆ ಮಲಗಿರಲು ಅವನಿಗೆ ಸೃಷ್ಟಿಯನ್ನು ರಚಿಸುವ ಇಚ್ಛೆಯಾಯಿತು. ಆಗ ತನ್ನ ನಾಭಿಯಿಂದ ಒಂದು ಕಮಲದ ಸೃಷ್ಟಿ ಮಾಡಿದನು ಅದರಿಂದ ಬ್ರಹ್ಮನು ಹುಟ್ಟಿದನು, ನಾರಾಯಣನು ಸೃಷ್ಟಿಯ ರಚನೆಯ ಕ್ರಮವನ್ನು ಬ್ರಹ್ಮನಿಗೆ ತಿಳಿಸಿ ಅದರ ನಿರೋಪವನ್ನು ಕೊಟ್ಟನು ಮತ್ತು ಅವನ ಸಹಾಯಕ್ಕಾಗಿ ವೇದಗಳನ್ನು ಕೊಟ್ಟನು. ಬ್ರಹ್ಮನು ಜೀವರಾಶಿಗಳ ರಚನೆಯ ನಂತರ ನಾಲ್ಕು ಯುಗಗಳ ರಚನೆ ಮಾಡಿದನು. ಅವುಗಳು ಕೃತಯುಗ, ತ್ರೇತಾಯುಗ, ದ್ವಾಪರಯುಗ ಮತ್ತು ಕಲಿಯುಗ. ಈ ಯುಗಗಳ ಲಕ್ಷಣವನ್ನು ಸಹ ಅವುಗಳಿಗೆ ಹೇಳಿದನು. ಕೃತಯುಗವೂ ಸಂಪೂರ್ಣ ಧರ್ಮಾಚರಣೆಯಿಂದ ಕೂಡಿದ್ದು ಆ ಸಮಯದ ಜನರು ಸತ್ವಗುಣ ಹೊಂದುತ್ತಾರೆ. ಹೀಗೆ ತ್ರೇತಾಯುಗ ಮತ್ತು ದ್ವಾಪರ ಯುಗಕ್ಕೂ ಹೇಳಿದನು. ಕಲಿಯುಗದ ಲಕ್ಷಣ ಬಹಳ ವಿಚಿತ್ರ, ಕಲಿಯುಗದಲ್ಲಿ ಜನರು ಅಸತ್ಯವಂತರೂ, ಧರ್ಮಕ್ಕೇ ವಿರೋಧ ಮಾಡುವವರೇ ಹೆಚ್ಚು. ಈ ಸಮಯದಲ್ಲಿ ಜನರ ಆಯುಷ್ಯವು 100 ವರ್ಷಗಳು ಮಾತ್ರ. ಈ ಸಮಯದಲ್ಲಿ ಯಾರು ಗುರುಗಳನ್ನ ನಂಬಿ ಬದುಕುತ್ತಾರೋ ಅವರಿಗೆ ಈ ಕಲಿಯ ಗುಣಗಳು ಬರುವುದಿಲ್ಲ ಅಂತ ಹೇಳಲಾಗಿದೆ`,
            kannada_p3: `ಗುರುಗಳ ಮಹಿಮಯೆನ್ನು ವರ್ಣಿಸಲು ಬ್ರಹ್ಮನು ಒಂದು ಕಥೆಯನ್ನು ಹೇಳಿದನು.
            ಹಿಂದೆ 'ವೇದಧರ್ಮ' ಎಂಬ ಮುನಿಯು ತನ್ನ ಪೂರ್ವಕರ್ಮವನ್ನು ಕಳೆದುಕೊಳ್ಳುವ ಸಲುವಾಗಿ ಕುಷ್ಠರೋಗಿಯಾಗಿ ಕಾಶಿ ಕ್ಷೇತ್ರದಲ್ಲಿ ತನ್ನ ಶಿಷ್ಯರಲ್ಲಿ ಒಬ್ಬನಾದ ದೀಪಕನೊಂದಿಗೆ ವಾಸಿಸುತ್ತಿದ್ದರು. ದೀಪಕನು ಒಂದೇ ಮನಸ್ಸಿನಿಂದ ಗುರುಗಳ ಸೇವೆಯನ್ನು ಮಾಡುತ್ತಿದ್ದನು. ರೋಗದಿಂದ ಬಳಲುತ್ತಿದ್ದ ಸಂದರ್ಭದಲ್ಲಿ ದೀಪಕನಿಗೆ ಬೈದರೂ ಅದನ್ನ ಮನಸ್ಸಿಗೆ ತೆಗೆದುಕೊಳ್ಳದೆ ಭಕ್ತಿಯಿಂದ ಸೇವೆ ಮಾಡುತ್ತಿದ್ದ. ಹೀಗೆ ಕೆಲವು ತಿಂಗಳುಗಳು ಕಳೆದಿರಲು ದೀಪಕನ ಗುರು ಭಕ್ತಿಗೆ ಮೆಚ್ಚಿ ಕಾಶಿ ವಿಶ್ವನಾಥನೇ ದೀಪಕನಿಗೆ ವರಕೊಡಲು ಪ್ರತ್ಯಕ್ಷನಾದನು ಆದರೇ, ದೀಪಕನು ಗುರುವಿನ ಅಪ್ಪಣೆಯಿಲ್ಲದೇ ಯಾವುದೇ ವರ ಬೇಡವೆಂದು ಅವನನ್ನು ಹಾಗೆ ಕಳುಹಿಸಿದನು. ಇದನ್ನು ಕೇಳಿ ನಾರಾಯಣನೂ ಕೂಡ ಅವನಿಗೆ ವರ ಕೊಡಲು ಬಂದಾಗ, ವರ ಕೊಡುವುದೇ ಆದರೆ ನನಗೆ ಗುರುವಿನ ಮೇಲೆ ಇನ್ನಷ್ಟು ಭಕ್ತಿ ಹೆಚ್ಚಾಗುವ ವರ ಕೊಡಲು ಕೇಳಿದನು. ಗುರುಗಳ ಮೇಲಿದ್ದ ಅವನ ಭಕ್ತಿಗೆ ಹರಿ-ಹರರೇ ಆತನಿಗೆ ವಲಿದರು. ಇದೇ ಗುರುವಿನ ಶಕ್ತಿ. ಕಾಶಿ ಕ್ಷೇತ್ರದಲ್ಲಿದ್ದ ಕಾರಣ ವೇದಧರ್ಮ ಮುನಿಯ ಪಾಪಗಳು ನಷ್ಟವಾದವು ಇದು ಕಾಶಿ ಕ್ಷೇತ್ರದ ಮಹಿಮೆಯಾಗಿದೆ`,
            kannada_h2: `ಈ ಅಧ್ಯಾಯದ ಸಾರಾಂಶ, ನಿಜವಾದ ಭಕ್ತರ ಮನಸ್ಸಿನಲ್ಲಿ ಗುರುಗಳು ಸದಾ ವಾಸಿಸುತ್ತಾರೆ ಎನ್ನುವುದಾಗಿದೆ`,
            img1: `/Images/narayan.jpeg`

        }
 } 
]

export default contents;